project: postgres-segundo-qa-database
database:
  engine: postgresql
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  name: ${POSTGRES_DB}
  bootstrap:
    db: ${POSTGRES_ROOT_DB}
    user: ${POSTGRES_ROOT_USER}
    password: ${POSTGRES_ROOT_PASSWORD}
  owner:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql_path: sql
  version_table: controle_versoes
  version_schema_file: versionamento.sql
  execution_order:
    - file: banco_ouros_fisico.sql
      mode: on_change
    - file: atualiza_lots_farm-owners.sql
      mode: once
    - file: dataload_inicial.sql
      mode: once
    - file: atualiza_password.sql
      mode: once
    - file: midas-user.sql
      mode: on_change
