ALTER TABLE lots
ADD COLUMN IF NOT EXISTS lots INTEGER NOT NULL DEFAULT 0
    CHECK (lots >= 0);

ALTER TABLE lots
ADD COLUMN IF NOT EXISTS cost DOUBLE PRECISION NOT NULL DEFAULT 0
    CHECK (cost >= 0);

ALTER TABLE farm_owners
ADD COLUMN IF NOT EXISTS first_acess BOOLEAN NOT NULL DEFAULT TRUE;
